config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :members
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :tasks
  validates :name, presence: true
  validates :age, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :member
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index # GET
    @members = Member.all
  end

  def new # GET
    @member = Member.new
  end

  def create # POST
    Member.transaction do
      member_params = params.require(:member)
        .permit(:name, :email, :age)

      @member = Member.new  member_params
      @member.save!
    end

  rescue
    render action: :new
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find params[:id]
  end

  def update
    Member.transaction do
      member_params = params.require(:member)
        .permit(:name, :email, :age)

      @member = Member.find params[:id]
      @member.attributes = member_params
      @member.save!
    end
    
  rescue
    render action: :new
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    Task.transaction do
      @task = Task.new params.require(:task)
                             .permit(:title, :member_id, :content)
      @task.save!
      redirect_to task_path(@task)
    end

  rescue
      render action: :new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    Task.transaction do
      @task = Task.find(params[:id])
      @task.update_attributes! params.require(:task)
                                     .permit(:title, :member_id, :content)
      redirect_to task_path(@task)
    end

  rescue
    render action: :edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/create.html.erb
<p>メンバーを作成しました</p>
<%= link_to '戻る', members_path %>

app/views/members/edit.html.erb
<%= form_for @member do |f| %>

<dl>
<dt>名前</dt>
<dd><%= f.text_field :name %></dd>
<dt>メールアドレス</dt>
<dd><%= f.text_field :email %></dd>
<dt>年齢</dt>
<dd><%= f.text_field :age %></dd>
</dl>

<%= f.submit '変更' %>

<% end %>

app/views/members/index.html.erb
<%= link_to '新規作成', new_member_path %>
<%= link_to 'CSV', members_path(format: 'csv') %>

<h1>メンバー一覧</h1>
<table>
  <thead>
    <tr><th>名前</th><th>メール</th><th>年齢</th></tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= member.age %></td>
        <td><%= link_to '詳細', member_path(member) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<%= form_for @member do |f| %>

<dl>
<dt>名前</dt>
<dd><%= f.text_field :name %></dd>
<dt>メールアドレス</dt>
<dd><%= f.text_field :email %></dd>
<dt>年齢</dt>
<dd><%= f.text_field :age %></dd>
</dl>

<%= f.submit '登録' %>

<% end %>

app/views/members/show.html.erb
<h1>メンバー詳細</h1>
<table>
  <thead>
    <tr><th>名前</th><th>メール</th><th>年齢</th></tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @member.name %></td>
      <td><%= @member.email %></td>
      <td><%= @member.age %></td>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_member_path(@member) %>

<h2>タスクリスト</h2>

<table>
  <thead>
    <tr><th>タイトル</th></tr>
  </thead>
  <tbody>
    <% @member.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= link_to '詳細', task_path(task) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/update.html.erb
<p>メンバーを更新しました</p>
<%= link_to '戻る', members_path %>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>

  <dl>
  <dt>メンバー</dt>
  <dd><%= f.collection_select :member_id,
                          Member.all, :id, :name %></dd>
  <dt>タイトル</dt>
  <dd><%= f.text_field :title %></dd>
  <dt>内容</dt>
  <dd><%= f.text_area :content %></dd>
  </dl>

  <%= f.submit '変更' %>

<% end %>

app/views/tasks/index.html.erb
<%= link_to '新規作成', new_task_path %>

<h1>タスク一覧</h1>
<table>
  <thead>
    <tr><th>メンバー</th><th>タイトル</th></tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.member.name %></td>
        <td><%= task.title %></td>
        <td><%= link_to '詳細', task_path(task) %></td>
        <td><%= link_to '削除', task_path(task) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>

  <dl>
  <dt>メンバー</dt>
  <dd><%= f.collection_select :member_id,
                          Member.all, :id, :name %></dd>
  <dt>タイトル</dt>
  <dd><%= f.text_field :title %></dd>
  <dt>内容</dt>
  <dd><%= f.text_area :content %></dd>
  </dl>

  <%= f.submit '登録' %>

<% end %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<dl>
<dt>メンバー</dt>
<dd><%= @task.member.name %></dd>
<dt>タイトル</dt>
<dd> <td><%= @task.title %></td></dd>
<dt>内容</dt>
<dd><%= simple_format @task.content %></dd>
</dl>

<%= link_to '編集', edit_task_path(@task) %>